sudo: required
services:
  - docker

before_install:
  - docker build -t dnmahendra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dnmahendra/react-test npm test -- --coverage

after_success:
  - docker build -t dnmahendra/multi-client ./client
  - docker build -t dnmahendra/multi-nginx ./nginx
  - docker build -t dnmahendra/multi-server ./server
  - docker build -t dnmahendra/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push these images to docker hub
  - docker push dnmahendra/multi-client
  - docker push dnmahendra/multi-nginx
  - docker push dnmahendra/multi-server
  - docker push dnmahendra/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-2-299028472933"
  bukcet_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
